### PR TITLE
Add Python 3.11.

### PR DESCRIPTION
**Pull request by bdice**
Adds support for Python 3.11.

xref: https://github.com/rapidsai/build-planning/issues/3

### CODE REVIEW

**Comment by jakirkham** [comment]
Noticing this error [on CI]( https://github.com/rapidsai/docker/actions/runs/8116731694/job/22187422577?pr=635#step:9:213 ):

```
#11 13.90 Looking for: ['rapids=24.04', 'dask-sql=2023.11', 'python=3.11', 'cuda-version=12.2', 'ipython']
#11 13.90 
#11 13.90 Could not solve for environment specs
#11 13.90 The following packages are incompatible
#11 13.90 ├─ cuda-version 12.2**  is requested and can be installed;
#11 13.90 ├─ python 3.11**  is installable and it requires
#11 13.90 │  └─ python_abi 3.11.* *_cp311, which can be installed;
#11 13.90 └─ rapids 24.04**  is not installable because there are no viable options
#11 13.90    ├─ rapids 24.04.00a would require
#11 13.90    │  └─ python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;
#11 13.90    ├─ rapids 24.04.00a would require
#11 13.90    │  └─ cuda-version >=11,<12.0a0 , which conflicts with any installable versions previously reported;
#11 13.90    └─ rapids 24.04.00a would require
#11 13.90       └─ python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported.
#11 ERROR: process "/bin/bash -euo pipefail -c mamba install -y -n base \\\n    \"rapids=${RAPIDS_VER}.*\" \\\n    \"dask-sql=${DASK_SQL_VER%.*}.*\" \\\n    \"python=${PYTHON_VER}.*\" \\\n    \"cuda-version=${CUDA_VER%.*}.*\" \\\n    ipython\nconda clean -afy\n" did not complete successfully: exit code: 1
------
 > [base 5/6] RUN <<EOF (mamba install -y -n base ...):
13.90 ├─ cuda-version 12.2**  is requested and can be installed;
13.90 ├─ python 3.11**  is installable and it requires
13.90 │  └─ python_abi 3.11.* *_cp311, which can be installed;
13.90 └─ rapids 24.04**  is not installable because there are no viable options
13.90    ├─ rapids 24.04.00a would require
13.90    │  └─ python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;
13.90    ├─ rapids 24.04.00a would require
13.90    │  └─ cuda-version >=11,<12.0a0 , which conflicts with any installable versions previously reported;
13.90    └─ rapids 24.04.00a would require
13.90       └─ python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported.
```

Are we using the nightly channel here?

**Comment by jakirkham** [comment]
As discussed offline, this is likely due to the fact we are missing the `integration` repo packages

Bradley started [a new GHA build]( https://github.com/rapidsai/integration/actions/runs/8116965078 ) to produce those

**Comment by jakirkham** [comment]
Ok things are looking better

[One job]( https://github.com/rapidsai/docker/actions/runs/8116731694/job/22188523537?pr=635#step:9:683 ) had a network error. We can restart that after the running jobs complete

**Comment by bdice** [comment]
Something was odd about the previous failures (I hadn't seen network issues like that before) so I pushed a new commit just to make sure everything is running from a fresh state.

**Comment by jakirkham** [comment]
A couple jobs failed. It looked like network issues. So restarted

**Comment by jakirkham** [comment]
Looks like we lost the cached images 😞 

Seeing this [on CI]( https://github.com/rapidsai/docker/actions/runs/8118829325/job/22265189360?pr=635#step:3:17 ):

```
Starting job container
  /usr/local/bin/docker pull rapidsai/staging:docker-notebooks-635-24.04a-cuda11.8-py3.9-amd64
  Error response from daemon: manifest for rapidsai/staging:docker-notebooks-635-24.04a-cuda11.8-py3.9-amd64 not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 5.831 seconds before retry.
  /usr/local/bin/docker pull rapidsai/staging:docker-notebooks-635-24.04a-cuda11.8-py3.9-amd64
  Error response from daemon: manifest for rapidsai/staging:docker-notebooks-635-24.04a-cuda11.8-py3.9-amd64 not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 1.368 seconds before retry.
  /usr/local/bin/docker pull rapidsai/staging:docker-notebooks-635-24.04a-cuda11.8-py3.9-amd64
  Error response from daemon: manifest for rapidsai/staging:docker-notebooks-635-24.04a-cuda11.8-py3.9-amd64 not found: manifest unknown: manifest unknown
  Error: Docker pull failed with exit code 1
```

**Comment by jakirkham** [comment]
Rerunning CI from scratch to see if this clears things up

**Comment by jakirkham** [comment]
Looks like this passes. Asking for an OPS review offline

**Review by raydouglass — APPROVED** [review]

**Pull request merged**
