### PR TITLE
resolve warnings about casing in Dockerfiles

### PR DESCRIPTION
**Pull request by jameslamb**
I've been seeing this build warning in logs here:

```text
 2 warnings found (use --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 37)
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 70)
```

([example build link](https://github.com/rapidsai/docker/actions/runs/9773984230/job/26981297565#step:9:826))

That comes from BuildKit's build checks (https://docs.docker.com/reference/build-checks/). Details on that specific warning: https://docs.docker.com/reference/build-checks/from-as-casing/.

This fixes it, to remove a source of noise in logs (and because I agree with the suggestion that capitalizing keywords approves readability a bit).

### CODE REVIEW

**Review by KyleFromNVIDIA — APPROVED** [review]

**Comment by jameslamb** [comment]
The notebook builds should hopefully be fixed once https://github.com/rapidsai/cuspatial/pull/1404 is merged

**Comment by jameslamb** [comment]
A couple of `cuspatial` notebooks are still failing. I've documented those in https://github.com/rapidsai/cuspatial/issues/1406

**Comment by jameslamb** [comment]
Tests are passing here... looks like the fixes from #690 helped!

**Comment by jakirkham** [comment]
Thanks James and Kyle! 🙏

**Pull request merged**
