### PR TITLE
remove delete-temp-images job

### PR DESCRIPTION
**Pull request by jameslamb**
Follow-up to #708.

Proposes completely removing the `delete-temp-images` job, in favor of relying on the scheduled nightly cleanup at https://github.com/rapidsai/workflows/blob/main/.github/workflows/cleanup_staging.yaml.

### Details

CI here writes images to the `rapidsai/staging` repo on DockerHub, then later copies them to individual user-facing repos.
To avoid those temporary CI artifacts piling up in the `rapidsai/staging` repo, pull requests and branch builds run a job called `delete-temp-images` which does what it sounds like.

In exchange for more aggressive cleaning, this job introduces significant complexity for development here. Most notably, we've observed several instances where that job deletes images before all CI jobs needing them have completed successfully, leading to all of CI needing to be re-run.

Significant effort has been put into trying to avoid that, and we've found it's been difficult to get it right:

some attempts:

* #702
* #708

a recent example:

* https://github.com/rapidsai/docker/pull/696#issuecomment-2299835638

### Ok so how will we clean up?

The workflow at https://github.com/rapidsai/workflows/blob/main/.github/workflows/cleanup_staging.yaml.

It runs once a day and deletes anything from `rapidsai/staging` that's more than 30 days old.

### Benefits of these changes

As described in https://github.com/rapidsai/docker/pull/708#discussion_r1718850401 ...

CI here will work as it does in other RAPIDS repos.... if any jobs fail for retryable reasons (like network issues), you can safely click "re-run failed jobs" and make incremental progress towards all builds passing.

Also reduces the need to maintain code that has to keep up with the DockerHub API in two places (by deleting `ci/delete-temp-images.sh` here).

### CODE REVIEW

**Review by bdice — APPROVED** [review]
Cool. This is what I hoped #708 would help with.

**Comment by jameslamb** [comment]
`cuspatial` notebook failures 😬 

```text
Error during notebook tests!
Errors during cuspatial/Taxi_Dropoff_Reverse_Geocoding.ipynb
Errors during cuspatial/trajectory_clustering.ipynb
```

([build link](https://github.com/rapidsai/docker/actions/runs/10480028357/job/29027948096?pr=709))

Those are both tested in `cuspatial` CI ([the are not excluded in this list](https://github.com/rapidsai/cuspatial/blob/c60bd4dfc25e62d68cdf520789c6c8bfc577724d/ci/test_notebooks.sh#L32)), so that means `cuspatial` CI will be blocked. Will open an issue there and link it here.

**Review by raydouglass — APPROVED** [review]

**Comment by bdice** [comment]
@jameslamb I am checking cuSpatial's CI with this PR: https://github.com/rapidsai/cuspatial/pull/1441#issuecomment-2302636097

**Comment by jameslamb** [comment]
Great, thanks for pushing this forward @bdice . Looks like CI there did fail on these same notebooks ([build link](https://github.com/rapidsai/cuspatial/actions/runs/10494807908/job/29072684373?pr=1441)), and that https://github.com/rapidsai/cuspatial/pull/1442 is up to hopefully fix it.

**Comment by mroeschke** [comment]
https://github.com/rapidsai/cuspatial/pull/1442 has been merged so hopefully a rerun of this PR should pass the CI now

**Comment by jameslamb** [comment]
Thanks as always @mroeschke !

I just restarted all CI jobs here (assuming we need to do rebuilds to pull in the newest `cuspatial`).

**Comment by bdice** [comment]
@jameslamb There was a solver error so I dropped Python 3.9 to make CI pass. See b6e37e3.

**Comment by jameslamb** [comment]
Ok sure, works for me. Thank you!

**Review by jakirkham — APPROVED** [review]
Thanks James! 🙏

Also thanks everyone who reviewed and pushed fixes here and elsewhere! 🙏

**Comment by jameslamb** [comment]
Given the set of approvals and passing jobs, I think this is ready to merge. Thanks yall.

**Comment by jakirkham** [comment]
Thanks James and everyone for reviewing! 🙏

**Pull request merged**
