### PR TITLE
[NO MRG] Test CI

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jakirkham** [comment]
One of the jobs had trouble during building finding the `rapids=24.08` package. Likely a network issue as the packages appear to be there and we haven't had issues in other builds. Restarted all jobs to have a clean build

**Comment by jameslamb** [comment]
thanks @jakirkham .

I just remembered I have #688, want to use that to continue testing CI? It isn't adding CUDA 12.5 support so shouldn't be blocked by `cuspatial`, and it at least should eventually be merged (to fix some very minor stylistic warnings).

I restarted CI there a few minutes ago.

**Comment by jakirkham** [comment]
We can certainly do that

Looks like we are down to the final 3 jobs here. So may just wait and see what happens

**Comment by jameslamb** [comment]
Looks like tests did pass here and in https://github.com/rapidsai/docker/pull/688! I'm going to merge https://github.com/rapidsai/docker/pull/688, and I think we can close this.

**Pull request closed without merging**
