### PR TITLE
Add Dask Labextension config

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Add some config for the Dask Jupyter Lab Extension to use `dask_cuda.LocalCUDACluster` by default.

The result of this means clicking the "New" button in the Dask extension will create a `LocalCUDACluster` instead of a `LocalCluster`.

image

cc @pentschev

### CODE REVIEW

**Review by pentschev — APPROVED** [review]
This is a great idea, thanks @jacobtomlinson ! I'm not sure if that's possible without changes in Dask itself, but could we also change the text to "Start New Dask _CUDA_ Cluster"? This is only a cosmetic clarification change, and I'm not sure if that's important, certainly I'd ignore it if that requires changes elsewhere.

**Comment by jacobtomlinson** [comment]
It's not possible right now. It's a good idea though. 

I'd like to improve the cluster creation in the Lab Extension generally at some point. So maybe it's something to tackle then.

**Comment by ajschmidt8** [comment]
@jacobtomlinson, sorry for the delay here. can you pull the latest changes into your branch here? I updated the GitHub Action name recently. I can merge after that.

**Comment by jacobtomlinson** [comment]
Thanks @ajschmidt8. Merged, regenerated and pushed.

**Review by ajschmidt8 — APPROVED** [review]

**Pull request merged**
