### PR TITLE
Add support for Ubuntu 24.04.

### PR DESCRIPTION
**Pull request by bdice**
Part of https://github.com/rapidsai/build-planning/issues/74.

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]

**Comment by jakirkham** [comment]
Not ideal, but let's try the old close and reopen. Especially now that CI will be less packed

**Comment by bdice** [comment]
This was failing to merge because of a branch protection on `pr-builder / run` when the job is actually titled `ci / docker / pr-builder / run`. This branch protection was automatically added during branch-24.12 creation. We will need to fix this in our release automation scripts.

**Pull request merged**
