### PR TITLE
Use UCX-Py 0.20

### PR DESCRIPTION
**Pull request by jakirkham**
cc @raydouglass @pentschev @quasiben

### CODE REVIEW

**Review by pentschev — APPROVED** [review]
Thanks @jakirkham !

**Review by dillon-cullinan — CHANGES_REQUESTED** [review]
This version should not be hardcoded into our templates. We should be programmatically getting it through our axis files.

**Comment by jakirkham** [comment]
Does that look better @dillon-cullinan?

**Comment by ajschmidt8** [comment]
> Does that look better @dillon-cullinan?

A few more changes will be needed. I'll make some updates to this PR for you John.

**Comment by jakirkham** [comment]
Thanks AJ! Sorry I don't know what I'm doing here 😅

**Comment by ajschmidt8** [comment]
> Thanks AJ! Sorry I don't know what I'm doing here

No worries! This repo is our responsibility :slightly_smiling_face:.

**Review by dillon-cullinan — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Comment by jakirkham** [comment]
Thank you both 🙏

**Pull request merged**
